---
galaxy_info:
  role_name: provision_ontap_volume
  author: team-storage
  description: Create/export a NetApp ONTAP volume on ServiceNow request
  license: MIT
  min_ansible_version: "2.15"
dependencies: []
